services:

  isbn_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'isbn_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  isbn_app:
    build: .
    ports:
      - '4200:4200'
    depends_on:
      - isbn_db
